apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp1
  namespace: miniapps
spec:
  selector:
    matchLabels:
      app: miniapp1
      namespace: miniapps
  template:
    metadata:
      labels:
        app: miniapp1
        namespace: miniapps
    spec:
      containers:
        - name: miniapp1
          image: ghcr.io/dracon/miniapp-start:v1.0.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-secret
